apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: developer
spec:
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIUE1IWUNBUUF3RkRFU01CQUdBMVVFQXd3SlpHVjJaV3h2Y0dWeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVHSDQxU3ZWa3lrekJobTV5NjNEWm52b3ZVQU1xdnNyMDc4ZWFSdEJkSkdPaUVCdVh5RDJuCjdMalBITGpoZUtILzNmQlNTbTVkS3lYK3A4SUQyZkZadUtBQU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRGwKUXFHZGtvRWEzWXYxRVNiZ3J4TDQvdTh5VnVnSkRrUDVpWHQxbVJjbGJnSWhBSmxvTTFDeEMzaWdqUVJpN3VseAoxcnFSdDRhSVgvS2UyS1V4S1R0WVZHV1EKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 31536000 # 1 year
 usages:
 - client auth
