apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: admin
spec:
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIY01JR0NBZ0VBTUNBeERqQU1CZ05WQkFNTUJXRmtiV2x1TVE0d0RBWURWUVFLREFWaFpHMXBiakJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkdhcjgxVU9QN0pZaU4yMzhkbk51RUNTZDVoMDNEb2tjOU9HCi8yQ3lBU3JOekY3dnRkTzJjWWYxcXRBRWIxV3cyT3RaUEJlNDdodGJIV282bVdDT1FLQ2dBREFLQmdncWhrak8KUFFRREFnTkpBREJHQWlFQXZrZ0llNHpkSzRzSDVQd3BhQ0IzTEVNWENkTW5DNDlLblhLcnJld0t4ZElDSVFEMAo3QTRrTFFDemNTSWJDMURsbnlSRXR1RkVOdGoxV2FHK2dEQ2VHSVQyVUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 31536000 # 1 year
 usages:
 - client auth
