version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beecrownd
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
