apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "giropops-senhas" "name" }}
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  type: {{ index .Values "giropops-senhas" "service" "type" }}
  ports:
    - protocol: TCP
      nodePort: 32500
      port: {{ index .Values "giropops-senhas" "service" "port" }}
      targetPort: {{ index .Values "giropops-senhas" "service" "targetPort" }}
      name: {{ index .Values "giropops-senhas" "service" "name" }}
