apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  replicas: {{ index .Values "giropops-senhas" "replicas" }}
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
        - name: {{ index .Values "giropops-senhas" "name" }}
          image: {{ index .Values "giropops-senhas" "image" }}
          imagePullPolicy: Always
          ports:
          {{- range index .Values "giropops-senhas" "ports" }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
          {{- end }}
          resources:
            limits:
              memory: {{ index .Values "giropops-senhas" "resources" "limits" "memory" }}
              cpu: {{ index .Values "giropops-senhas" "resources" "limits" "cpu" }}
            requests:
              memory: {{ index .Values "giropops-senhas" "resources" "requests" "memory" }}
              cpu: {{ index .Values "giropops-senhas" "resources" "requests" "cpu" }}
