/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAINED_H_RPCGEN
#define _CHAINED_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct lista {
	int value;
	struct lista *nxt;
};
typedef struct lista lista;

typedef lista Lista;

#define SOMA_LISTA 0x13
#define SOMA_LISTA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMAL 1
extern  int * somal_1(Lista *, CLIENT *);
extern  int * somal_1_svc(Lista *, struct svc_req *);
extern int soma_lista_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMAL 1
extern  int * somal_1();
extern  int * somal_1_svc();
extern int soma_lista_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lista (XDR *, lista*);
extern  bool_t xdr_Lista (XDR *, Lista*);

#else /* K&R C */
extern bool_t xdr_lista ();
extern bool_t xdr_Lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAINED_H_RPCGEN */
