/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chained.h"


void soma_lista_1(char *host, Lista* begin)
{
	CLIENT *clnt;
	int  *result_1;
	/* Lista somal_1_arg; */

#ifndef	DEBUG
	clnt = clnt_create (host, SOMA_LISTA, SOMA_LISTA_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = somal_1(begin, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
  int list_size, i;
  Lista *lst, *begin, *aux;

	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
    printf("error, right way to use is %s server_host num1 num2 num3...\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	// Fill List with user input
  list_size = argc - 2;
  begin = (Lista*) malloc(sizeof(Lista));
  lst = begin;
  for (int i = 0; i < list_size; i++) {
    lst->value = atoi(argv[i + 2]);
    lst->nxt = (Lista*) malloc(sizeof(Lista)); 

    aux = lst;
    lst = lst->nxt;
  }

  free(aux->nxt);
  aux->nxt = NULL;
  // -------------------------

	soma_lista_1(host, begin);
	exit (0);
}
