apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  namespace: giropops
spec:
  selector:
    app: giropops-senhas
  ports:
    - name: curl
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: ingress
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
