apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: platform
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlIaU1JR0lBZ0VBTUNZeEVUQVBCZ05WQkFNTUNIQnNZWFJtYjNKdE1SRXdEd1lEVlFRS0RBaHdiR0YwWm05eQpiVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTThGcFU3QjlKQlZDNERDQ1liOWhNMXhnQTU1CjBWNXd4UElWZjZ2WStnVG5IZDNCWnlOS3lyNnM0VkdkVkdiN2syc0tEUkJZNGpuak1MOVZaM1BjQ3VDZ0FEQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBaDc4VUx5bTA5R0I2UnFkSmx4RTI2QjBUY3V0d2ZFSThDNlM5Rm4yRQo2bzRDSVFDODNTWlpjWHhCL3lTWFc5Z1VyTFYwVDEvMUhDU1ZRdzlvZkd2elFIU3ZuZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000 # 1 year
  usages:
    - client auth
