/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "variadic.h"
#include <stdio.h>

int * somav_1_svc(vetint *argp, struct svc_req *rqstp)
{
	static int  result;
	int i = 0;
	result = 0;

  while (i < argp->vetint_len) {
    result += argp->vetint_val[i];
    i++;
  }
  printf("sum: %d\n", result);


	return &result;
}
