/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VARIADIC_H_RPCGEN
#define _VARIADIC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int vetint_len;
	int *vetint_val;
} vetint;

#define SOMA_VARIADIC 0x9
#define SOMA_VARIADIC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMAV 1
extern  int * somav_1(vetint *, CLIENT *);
extern  int * somav_1_svc(vetint *, struct svc_req *);
extern int soma_variadic_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMAV 1
extern  int * somav_1();
extern  int * somav_1_svc();
extern int soma_variadic_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vetint (XDR *, vetint*);

#else /* K&R C */
extern bool_t xdr_vetint ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VARIADIC_H_RPCGEN */
