/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "variadic.h"
#include<stdio.h>
#include <stdlib.h>


void soma_variadic_1(char *host, vetint* l)
{
	CLIENT *clnt;
	int  *result_1;
	/* vetint  somav_1_arg; */

#ifndef	DEBUG
	clnt = clnt_create (host, SOMA_VARIADIC, SOMA_VARIADIC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = somav_1(l, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/* typedef struct { */
/* 	u_int vetint_len; */
/* 	int *vetint_val; */
/* } vetint; */

int main (int argc, char *argv[])
{
	char *host;
	vetint l;

  if (argc < 3) 
  {
    printf("error, right way to use is %s num1 num2 num3...\n", argv[0]);
    exit(1);
  }

  l.vetint_len =  argc - 2;
  l.vetint_val = (int*) malloc(sizeof(int) * l.vetint_len);

  for (int i = 0; i < l.vetint_len; i++) 
    { l.vetint_val[i] = atoi(argv[i + 2]); }

	host = argv[1];
	soma_variadic_1 (host, &l);
	exit (0);
}
